### ISSUE TITLE
Cannot work with magisk

### ISSUE THREAD

**Issue by wzhy90** [cswl/tsu#10]
Magisk version is 12.6. Maybe 13.X is still not working.

**Comment by C4droid** [comment]
in magisk 13.3 ,tsu still not work

**Comment by urain39** [comment]
https://github.com/cswl/tsu/pull/6

**Comment by urain39** [comment]
See this PR: https://github.com/cswl/tsu/pull/6

**Comment by wzhy90** [comment]
@urain39 Still has wrong PATH.
```
$ tsu
bash-4.4# echo $PATH
/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
bash-4.4#
```

**Comment by wzhy90** [comment]
@urain39 Add this text in the exec line
```PATH=$PATH```
then become like this
```exec ..........LD_LIBRARY_PATH=..... PATH=$PATH .........```

**Comment by C4droid** [comment]
>I would say it's a termux issue, because "su" itself works fine.
And it definitely works with the "su" from termux not any other probably in path (dircetly called with "/data/data/com.termux/files/usr/bin/su".
But "tsu" searches for "su" only in two hardcoded paths ("/system/xbin/su" and "/su/bin/su") instead using its own su, which searches in "/system/xbin/su", "/system/bin/su", "/su/bin/su", "/sbin/su" and "/magisk/.core/bin/su".

**Comment by Jolanrensen** [comment]
When manually adding /sbin/su to tsu I still get the CANNOT LINK EXECUTABLE error in termux...

**Comment by cswl** [comment]
https://github.com/cswl/tsu/commit/810c5967233962e2972991732ff08ef72bb5eb1e has been merged.
/magisk/.core/bin/su should be in search path now

**Comment by cswl** [comment]
Also https://github.com/cswl/tsu/commit/717b902303a9afd546e46722f36feca549376471 

Once the package is available in termux repos.. Im gonna close this
