### ISSUE TITLE
Tsu doesnt find su on kitsune mask 27.0 (Magisk delta)

### ISSUE THREAD

**Issue by gixousiyq** [cswl/tsu#105]
Kitsune mask (magisk delta) changed its su path from /system/bin to /apex/com.android.runtime/bin which breaked tsu

**Comment by gixousiyq** [comment]
A quick fix or workaround for this right now is to pull sudo from /data/data/com.termux/files/usr/bin/sudo and using any text editor to edit the line 281 or the function
SU_BINARY_SEARCH=("system/xbin/su" "/system/bin/su")
To 
SU_BINARY_SEARCH=("/debug_ramdisk/su" "/system/bin/su")
And then save the file
Then replace the one in .../files/usr/bin/sudo using anyway you want, for me i used dd (Ik theres better ways but whatever) Use this command to do it
dd if=/path/to/the/edited/sudo/file of=/data/data/com.termux/files/usr/bin/sudo
And you are ready to go!
Hope this helps anyone

**Comment by gixousiyq** [comment]
Magisk delta reverted this
Also dont use this bullshit method in the future

**Comment by CyberstormFox** [comment]
Current magisk canary build 28103 was affecting "tsu" until that small edit in the search path for the su command, fixed it for now. "su" would never be in the "/system/bin" path of most ROMS unless root is built in, and on my (Oneplus 10T) there was no "/system/xbin", but the location listed was indeed where magisk, and its su is hidden.
