### ISSUE TITLE
no binary found

### ISSUE THREAD

**Issue by Systemad** [cswl/tsu#11]
running `tsu` give the output

>"No superuser binary detected. \n"
>"Are you rooted?

I can confirm that su is in /sbin/ folder
Using magisk 14.3

**Comment by cswl** [comment]
I did merge the magisk patch..  
I dont have magisk installed myself to test it..

Can you show the output of 
```
bash -x $(which tsu)
```

**Comment by cswl** [comment]
Never mind.. I made a slight error.. Since I use SuperSU it ran fine on mine..

should be fixed in https://github.com/cswl/tsu/commit/f0d3a5c6d179c34be18fb91b14f2f3da2100365a
