### ISSUE TITLE
Not work on mtk6735(arm64)

### ISSUE THREAD

**Issue by LostGamerHL** [cswl/tsu#15]
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": cannot locate symbol "SSL_session_reused" referenced by "/system/lib64/libmtk_symbols.so"...                                             Aborted

**Comment by cswl** [comment]
Does `tsu -p` works?

**Comment by LostGamerHL** [comment]
Oh, sorry.
It's works. Thanks
