### ISSUE TITLE
Falls on a loop if command is placed on bashrc

### ISSUE THREAD

**Issue by sjd1337** [cswl/tsu#16]
I added the 'tsu' command on the bash.bashrc file so whenever I start the app I get a root shell immediately. Though, once the app is started the terminal just constantly resets. I know it's supposed to reset once and that does happen when I start the app and TYPE OUT the command but placing the command on bashrc just throws the terminal in this infinite loop.

**Comment by cswl** [comment]
`tsu` starts the user shell.. in your case bash.. which i think reads the `.bashrc` again...  causing an infinite loop..

I think you can do a check in `bashrc` to see if you're not already root and then load `tsu` only..  
Let me know if this works

`[[ $(whoami) == 'root' ]]  || tsu`

**Comment by sjd1337** [comment]
Thank you. It worked.

**Comment by cswl** [comment]
Glad to know it worked for you....  hadn't checked the command myself..

Be sure to star the project if you havent already!!  :star:
