### ISSUE TITLE
Invalid option 

### ISSUE THREAD

**Issue by Arsik0153** [cswl/tsu#18]
After installing I wrote "tsu" and I have error:
enter main
/system/xbin/su: invalid option -- -

I think this error there section:

if [ -z "$USER_COMMAND" ]; then
  exec "$SU_BINARY" --preserve-environment -c "LD_LIBRARY_PATH=$OLD_LIBRARY_PATH PATH=$PATH $ROOT_SHELL"
else
  exec "$SU_BINARY" --preserve-environment -c "LD_LIBRARY_PATH=$OLD_LIBRARY_PATH PATH=$PATH $USER_COMMAND"

fi

**Comment by MrMiddle** [comment]
It seems the xbin/su does not need any parameters.(for me,and the error is the same with you).so just remove xbin/su from the exec loop,then insert the command "exec /system/xbin/su" before the exec block,it will be right and keep the path

**Comment by cswl** [comment]
Which `su` are you using?
