### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by salvomic** [cswl/tsu#19]
Having installed tsu, with `tsu - A` I get `/data/data/com.termux/files/usr/bin/tsu: 139: exec: :Permission denied`
Any help, please?

**Comment by cswl** [comment]
Which `su` are you using...  

Also could you post the output of:
`bash -x $(which tsu)`

**Comment by salvomic** [comment]
the output is:
/data/data/com.termux/files/usr/bin/tsu

**Comment by cswl** [comment]
That's just the output for which..  bash didn't run it..
I will push a debug flag...   but for now.. could you run... 

```
bash -x /data/data/com.termux/files/usr/bin/tsu
```

**Comment by salvomic** [comment]
thanks!
I get the output in the attached image...
![img_3531](https://user-images.githubusercontent.com/37556565/38457290-95aac8da-3a8e-11e8-9442-b7e207cd7aa6.JPG)

**Comment by cswl** [comment]
From the output it seems it couldnt find the `su` binary..  

Are you rooted?  
Which superuser are you using.. SuperSU or your ROM

**Comment by salvomic** [comment]
no, I'm operating in a Huawei Mediapad M5 that apparently is not "root-able" (or not so easy "root-able")...

**Comment by zArubaru** [comment]
Hey, having similar issues, though my device has been rooted with SuperSU, here's some useful output:

```
$ tsu
# ls
bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied
# bash -x "$(which tsu)"
bash: /data/data/com.termux/files/usr/bin/applets/which: Permission denied
bash: /data/data/com.termux/files/usr/bin/bash: Permission denied
# exit
exit
$ bash -x "$(which tsu)"
+ getopts :aehps:c opt
+ test -z /data/data/com.termux/files/usr
+ test -n ''
+ test -n ''
+ LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
+ test -n ''
+ test -z ''
+ test -x /data/data/com.termux/files/home/.termux/shell
+ test -x /data/data/com.termux/files/usr/bin/bash
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/bash
+ OLD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
+ '[' -e /sbin/magisk ']'
+ for s in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /su/bin/su ']'
+ SU_BINARY=/su/bin/su
+ for s in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /sbin/su ']'
+ for s in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /system/xbin/su ']'
+ for s in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /system/bin/su ']'
+ '[' -z '' ']'
+ exec /su/bin/su --preserve-environment -c 'LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets /data/data/com.termux/files/usr/bin/bash'
bash-4.4# exit
exit
$ which su
/data/data/com.termux/files/usr/bin/su
$
```

**Comment by cswl** [comment]
Looks like youring using Systemless Supersu... 

And root isn't able to launch termux binaries..

Could you also post the output of.. running as not root..
`ls -l /data/data/com.termux/files/usr/bin/bash`

**Comment by salvomic** [comment]
`ls -l /data/data/com.termux/files/usr/bin/bash`
I get:
`-rwx------ 1 u0_a133 u0_a133 733224 Apr 3 22:44 /data/data/com.termux/files/usr/bin/bash` (green command, so the command exists)...

**Comment by cswl** [comment]
You shouldnt run `apt-get` with `tsu`.

Which `su` are you using.. and which Android version..
Sounds like an issue with permissions

**Comment by MrChrootInside** [comment]
hey i have a problem with my termux, can you guys help me?, when i run tsu command in my termux i do not enter the root mode can you guys petrify me?

**Comment by MrChrootInside** [comment]
hey are you guys can help me? when I type the command tau and run it appears the response as below, do you know what my problem and my termux? 
$ tsu
unknown option -- preserve-environment
Usage: su [options] [args...]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -cn, --context CONTEXT        switch to SELinux CONTEXT before invoking
  -d, -ad, --daemon, --auto-daemon
                                start the su daemon
  -i, --install                 check and repair su files
  -h, --help                    display this help message and exit
  -v, -V, --version             display version number and exit

Usage#2: su uid COMMAND...
$

**Comment by Harshiv-Patel** [comment]
I face a "permission denied" issue as well:

`$ tsu
$ ls
bash: /data/data/com.termux/files/usr/bin/ls: Permission denied
$ env
bash: /data/data/com.termux/files/usr/bin/env: Permission denied

The Shell prompt is ( possibly other environment variables too) preserved, with color.
Rooted with Magisk v16.
Running Android Lollipop 5.1.1
CPU arch : armv7l.

**Comment by haxersworld** [comment]
Has this issue have anything to do with SElinux mode???? And has this issue been resolved?

**Comment by Harshiv-Patel** [comment]
The issue has not been resolved for me so far. Have been trying to build a permissive kernel (for Sm-E700H)but not successful yet.

**Comment by S0U1SB4N3** [comment]
there is clearly an issue with permissions here can you show an android non-rooted user how to give file permissions to the TSU so it can intern tau <command> without getting the 139: permission denied error ?

**Comment by cswl** [comment]
Closing in favor of: https://github.com/cswl/tsu/issues/30
