### ISSUE TITLE
Touchscreen and key combinations not working in aps running with tsu

### ISSUE THREAD

**Issue by Ksnz** [cswl/tsu#20]
It just send keycodes to screen in apps lilke mc or htop
no mater if i try touch F10 or press Volume Up+0
![Image](https://i.imgur.com/qoNAKtJ.png)

**Comment by Ksnz** [comment]
Magisk updating fixed this

**Comment by mvallerie** [comment]
I'm having the exact same issue. If relevant, I'm not using Magisk but LineageOS 15.1 with its official su addon.

**Comment by cswl** [comment]
Didnt notice this.. since it was closed...

I think because the `su` is interpreting the escape codes..
