### ISSUE TITLE
tsu wrapper crashed with magisk 16.4

### ISSUE THREAD

**Issue by fhoshino** [cswl/tsu#21]
same issue as
https://github.com/termux/termux-app/issues/672
which has been fixed

**Comment by cswl** [comment]
> Remove all 64-bit binaries as there is no point in using them; all binaries are now 32-bit only.

Yeah fuck aarch64 .. which is what most new phones use .. 
Thanks to @Grimler91 for the PR fix..

I have merged it.. but I need time to update it to Termux repo..

Keeping this open to track that

**Comment by tjsdev** [comment]
CANNOT LINK EXECUTABLE "/sbin/su": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit

**Comment by cswl** [comment]
PR Merged. https://github.com/cswl/tsu/pull/22
