### ISSUE TITLE
tsudo removes quotes from commands

### ISSUE THREAD

**Issue by 0x72** [cswl/tsu#23]
``` bash
$ tsudo 'mkdir 'test1 test2''
$ ls -l
test1
test2
```

Correct output should be one directory with the name 'test1 test2', not two directories.

**Comment by 0x72** [comment]
Thank you! I wrongly assumed that you can nest single quotes in bash from the fact that double quotes are nestable.

**Comment by cswl** [comment]
This has to do with how the shell handles arguments.. and not with `tsudo` itself..

I'm glad you found the solution...  
Closing this for now
