### ISSUE TITLE
Tsu is working but can't see anything I typed on.

### ISSUE THREAD

**Issue by kiana22** [cswl/tsu#25]
Hello, I am really happy knowing about tsu, it worked though, however, on terminal, I can't seem to see words/strings i am typing into, but I am still getting response or results it's working, it's just I can't see anything I input on the terminal. 

Help please!

**Comment by cswl** [comment]
Hi.. the issue might have to do with https://github.com/cswl/tsu/issues/27

The TERM variable isn't being set..

**Comment by genelocated** [comment]
I also have the input problem. On my Android Pie device, I can type in commands but when I press backspace, it shows another space instead of removing a character. Finally I added `export TERM=xterm-256color` to `.zshrc` and solved this.
