### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by Lucas03lescure** [cswl/tsu#26]
Im using Magisk v17.0, i have granted root acces to termux,and im using an s7 edge.

when i type tsu this shows up:

bash: /data/data/com.termux/files/usr/libexec/termux/command-not-found: Permission denied

please help

**Comment by cswl** [comment]
On Magisk 17.1 
I dont get this error.

However I do get.
```
Permission denied
```

**Comment by cswl** [comment]
Closing in favor of: #30
