### ISSUE TITLE
CANNOT LINK EXECUTUBALE

### ISSUE THREAD

**Issue by tayheard** [cswl/tsu#29]
Hi..I keep getting the below error everytime i try to use tsu to drop to root shell,i have su installed
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": cannot locate symbol "ucnv_open_56" referenced by "/system/lib/libmtk_symbols.so"...
Please help

**Comment by tayheard** [comment]
A simple tsu -p did the trick...

**Comment by cswl** [comment]
`libmtk` are you using an MTK chipset device?

Would be nice if you could give your system details.. so I can fix it upstream

**Comment by tayheard** [comment]
Yes, I'm using an infinix MTK device that is rooted with Su..what system details do you need exactly?
