### ISSUE TITLE
Be a bit verbose when su is not present

### ISSUE THREAD

**Issue by exploide** [cswl/tsu#3]
Currently, `tsu` does nothing and silently exits when the phone is not rooted and there is no `su` binary. It would be nice to display a similar message like the dummy `su` shipped with `termux-tools` (maybe by invoking exactly this).

**Comment by cswl** [comment]
Good point.

**Comment by cswl** [comment]
I added this message:
https://github.com/cswl/tsu/commit/717b902303a9afd546e46722f36feca549376471
