### ISSUE TITLE
tsudo always default at '/'

### ISSUE THREAD

**Issue by lildevilx** [cswl/tsu#32]
So in termux your user home is defaulted (least in my case) `/data/data/com.termux/files/home/` 
so say when i try to do `tsudo ./run.sh` it will try to run it from `/run.sh` instead of `/data/data/com.termux/files/home/run.sh` 
any way to change the default path on tsudo to where ever i run the command?

**Comment by cswl** [comment]
Hmm.. I'm reworking `tsudo` and `tsu` for now
I will keep you updated..

**Comment by cswl** [comment]
Fixed in v8.3.2 update.
