### ISSUE TITLE
Permission denied on Nougat

### ISSUE THREAD

**Issue by Lucas03lescure** [cswl/tsu#42]
hi i have a samsung galaxy S7 edge (SM-G735f) rooted it using Magisk SU which is currently at V 1.18.1   I have troubles to execute commands some of them work (ex: echo) but others don't (like whoami and ls). When they don't i get this message:

bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied

Help would be much appreciated

**Comment by GetRektBoy724** [comment]
I get this to on android 8.1.0 or nougat
