### ISSUE TITLE
tsu outputs this:

### ISSUE THREAD

**Issue by T4P4N** [cswl/tsu#43]
I've already opened a issue in termux packages.
https://github.com/termux/termux-packages/issues/3917
Is this due to magisk update?
my magisk version is:
19.2(19200)
And magisk manager version is:
7.2.0(213)
And android version is
Android 8.1.0 Oreo

**Comment by T4P4N** [comment]
Now fixed

**Comment by githubpew** [comment]
THANK YOU :)
