### ISSUE TITLE
tsu CANNOT LINK EXECUTABLE DEPENDENCIES: library "libandroid-support.so" not found #

### ISSUE THREAD

**Issue by ahd778** [cswl/tsu#47]
plz help me
i spent months to root termux but always i get this
tsu
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libandroid-support.so" not found
#

imp.notes:
galaxy j3119
magisk 19.2.3
when i installed termux and update and upgrade for the first time , termux ask me to say yes or no for installing Bash 5.0.7-5 over 5.0.7.-1.. and i set yes. is that related?

another thing i didnt installed busybox but i installed busybox module of magisk only. is that related?

plz anyone help me ..

**Comment by ahd778** [comment]
![Uploading Screenshot_٢٠١٩-٠٨-٠٦-٠٨-٣١-٥٠.png…]()
![Uploading Screenshot_٢٠١٩-٠٨-٠٦-٠٨-٣١-٢٢.png…]()
![Uploading Screenshot_٢٠١٩-٠٨-٠٦-٠٨-٣١-١٦.png…]()
![Uploading Screenshot_٢٠١٩-٠٨-٠٦-٠٨-٣١-١٠.png…]()

**Comment by mashen11** [comment]
How to solve this problem?

**Comment by cswl** [comment]
Fixed in v8.3.2 update.  The old one had lot of problems

Now available with `pkg install tsu`
