### ISSUE TITLE
Tsu v8.0.0.a

### ISSUE THREAD

**Issue by gokaybiz** [cswl/tsu#53]
https://github.com/cswl/tsu/releases/download/v8.0.0.a%2B/tsu_8.0.0a+_all.deb
I installed this version but when i try to call, termux returns; "The program tsu is not installed. Install it by executing: pkg install tsu"
And If I try pkg install tsu command, 
It returns
"0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded."
I'm very confused about that.

**Comment by cswl** [comment]
Hmm, wait I will upload another 8.1.0 build

**Comment by cswl** [comment]
The new build should be updated and fix this issue..

 Please re-open in case you have face any more
