### ISSUE TITLE
tsu is looking for su in the wrong place

### ISSUE THREAD

**Issue by marmistrz** [cswl/tsu#54]
I'm running LineageOS 14.1 on OnePlus3, tsu 8.2.0, termux 0.94. The device is rooted using the official LineageOS su package. `tsu` fails with:
```
/sbin/su: Permission denied
```
Because on my device the whole `/sbin/` directory is inaccessible for non-root users. On the other hand, the `su` binary is present at `/system/bin/su` and just calling `su` successfully obtains root privileges.

/edit: the same issue occurs on LineageOS 16.0, Xiaomi Redmi 3s (land)

**Comment by cswl** [comment]
Intresting.. I totally forgot to check if the /sbin/ is acessible or not.. 
I will add a check today for Lineageos behavior

**Comment by marmistrz** [comment]
Just for completeness: after updating tsu to 8.2.0-1:
```
$ tsu
/data/data/com.termux/files/usr/bin/tsu: line 187: /sbin/su: Permission denied
#
```
So even though `/sbin/su` is inaccessible: 
1. root privileges are obtained
2. `PATH` is **not** modified and the termux binaries are not accessible "out of the box"

**Comment by cswl** [comment]
Please output `tsu --D` I really need to check this Magisk vs Lineage behavior

**Comment by marmistrz** [comment]
```
$ tsu --D
+ TERMUX_FS=/data/data/com.termux/files
+ TERMUX_PREFIX=/data/data/com.termux/files/usr
+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ROOT_HOME=/data/data/com.termux/files/home/.suroot
+ ANDROIDSYSTEM_PATHS=/system/bin:/system/xbin
+ ANDROIDSYSTEM_ASROOT_PATHS=/bin:/xbin
+ BB_MAGISK=/sbin/.magisk/busybox
+ [[ '' == true ]]
+ [[ -z '' ]]
+ SWITCH_USER=
+ declare -A EXP_ENV
+ root_shell_helper
+ '[' -n '' ']'
+ '[' '' = system ']'
+ test -x /data/data/com.termux/files/home/.termux/shell
+ test -x /data/data/com.termux/files/usr/bin/bash
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/bash
+ [[ '' == true ]]
+ STARTUP_SCRIPT=/data/data/com.termux/files/usr/bin/bash
++ /sbin/su -v
/data/data/com.termux/files/usr/bin/tsu: line 187: /sbin/su: Permission denied
+ [[ '' == \2\0*\M\A\G\I\S\K\S\U ]]
+ for SU_BINARY in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /su/bin/su ']'
+ for SU_BINARY in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /sbin/su ']'
+ for SU_BINARY in '/su/bin/su' '/sbin/su' '/system/xbin/su' '/system/bin/su'
+ '[' -e /system/xbin/su ']'
+ exec /system/xbin/su -c 'LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so /data/data/com.termux/files/usr/bin/bash'
```

**Comment by cswl** [comment]
Can you try this next version.
You can easily try it with.. 

```
curl -L "https://raw.githubusercontent.com/cswl/tsu/next/shell/tsu.sh"  > "$PREFIX/bin/tsu" 
```

**Comment by marmistrz** [comment]
The new version works perfectly. Thanks!

**Comment by cswl** [comment]
Thanks for reporting.
Please dont hesitate to open another issue if you encounter any bugs.
