### ISSUE TITLE
tsu in termux shows No superuser binary detected. Are you rooted?

### ISSUE THREAD

**Issue by mazhe1988** [cswl/tsu#55]
I use latest version of magisk (87de0e7a(20408)) on my dell labtop with bliss os.
Tsu was not working. I am sure I have the correct binary su file in the right place. 
Other app works fine on root permission requst.

**Comment by cswl** [comment]
Uhh... Can you run `tsu --D` and post the output ..
And also do a.. `ls /sbin/`

It enables debug output..

**Comment by mazhe1988** [comment]
I somehow figured out by myself. I change the Tsu file line 187:
(if [[ "$(/sbin/su -v)" == "20"*"MAGISKSU" ]]; then) to (if [[ "$(/sbin/su -v)" == "87de0e7a:MAGISKSU" ]]; then).  This version number is the number i got by run su -v on my computer. And the Tsu works. 
But this morning I updated the tsu.  The line 187 was back to the original setup. The tsu is still working right now. I don't know the reason. Sorry for my bad english. You may close this.

**Comment by cswl** [comment]
Oh.. wait I think your'e using Magisk Canary.. ?

**Comment by mazhe1988** [comment]
I download magisk manager from apkmirror. it should be. I am not sure.

**Comment by shemanshu1511** [comment]
> Uhh... Can you run `tsu --D` and post the output ..
> And also do a.. `ls /sbin/`
> 
> It enables debug output..



> Uhh... Can you run `tsu --D` and post the output ..
> And also do a.. `ls /sbin/`
> 
> It enables debug output..

![IMG_20200508_143231](https://user-images.githubusercontent.com/56867482/81390296-cd7def00-9138-11ea-9251-9b3cf275f60f.jpg)


> Uhh... Can you run `tsu --D` and post the output ..
> And also do a.. `ls /sbin/`
> 
> It enables debug output..

![IMG_20200508_143231](https://user-images.githubusercontent.com/56867482/81390335-dcfd3800-9138-11ea-9d65-3e9eb3c437d8.jpg)
 

Sir, New Version is kinda buggy no "tsudo" Available

**Comment by shemanshu1511** [comment]
Can i Know way to downloadgrade for temporary time ?

**Comment by cswl** [comment]
@shemanshu1511 It has been renamed to `sudo` for convinence.. 

Please open a new issue.. if you have further concerns

**Comment by shemanshu1511** [comment]
> @shemanshu1511 It has been renamed to `sudo` for convinence..
> 
> Please open a new issue.. if you have further concerns

Hmm, Ok Thanks Alot....😊

**Comment by cswl** [comment]
Should be fixed in v8.3.2 update.

Now available with `pkg install tsu`
