### ISSUE TITLE
tsu command only works with root

### ISSUE THREAD

**Issue by denisde4ev** [cswl/tsu#60]
![Screen Capture_20200513002044](https://user-images.githubusercontent.com/40498286/81746966-fd6a2100-94af-11ea-84d7-a704ddc75cf9.png)

tsu only works on root and is even worse when passed username
at least same username should result same result

I am trying to back to user of Termux from root. i have tried `HOME=/data/...../home PATH=/data/...../sbin  su u0_a194 -s /data/...../bash` but doesn't seem to work properly

port 22 for ssh can not be used without root and when start sshd as root I login in root from ssh.

**Comment by cswl** [comment]
There is no `-c` option in tsu..  And the `-s` is meant to change the shell like bash/sh

You can use `sudo ` which comes with `tsu` to run single commands as root with proper `PATH` passed in..

Should prolly include this in help text..

![20200513_173759](https://user-images.githubusercontent.com/12976647/81809112-52d61a80-9510-11ea-8824-f20498666a88.jpg)

**Comment by denisde4ev** [comment]
This didn't work for me. I have already tried reinstalling **tsu**

![Screen Capture_select-area_20200513222757](https://user-images.githubusercontent.com/40498286/81856200-27334e80-9569-11ea-8e56-dfc492a9da21.png)

even hardcoding user on line 127 in tsu in bin folder:

![Screen Capture_select-area_20200513223608](https://user-images.githubusercontent.com/40498286/81856923-2818b000-956a-11ea-957d-7d0201bf767a.png)

**Comment by denisde4ev** [comment]
Ignore wast comment, I was using Termux tsu version 8.3.2

after cloning repo - version 8.4.2 :
![image](https://user-images.githubusercontent.com/40498286/81858854-0967e880-956d-11ea-948d-31e79952d246.png)

now works slightly better but still not works as it should:
(port 22 cant be used without root)
![image](https://user-images.githubusercontent.com/40498286/81868163-8fd6f700-957a-11ea-9eb3-67af4327feb5.png)

this  `HOME=$HOME bash` works on my linuxls PC

**Comment by cswl** [comment]
Ah, I can see the problem..  Im not checking if Termux user can access the Termux binaries..

Also I think sshd cant automatically start with different user.. cause its patched in termux to run in single user mode
