### ISSUE TITLE
Environmental variables are not set after issuing "tsu"

### ISSUE THREAD

**Issue by staunch-thomas** [cswl/tsu#65]
I have LineageOS 17.1 on Samsung Galaxy S4 LTE.

The latest update of *tsu* to version 8.5.1 broke my usual workflow.

Now, when I start *tsu* in Termux, I don't get my fancy command prompt ($PS1 is not set) but just one symbol "#". When I run "vim somefile.txt" inside of *tsu*, *vim* doesn't have any of the settings from my .vimrc file and .vim directory. Actually, all settings from my .bashrc are not used either, e.g. the variable $EDITOR is not set.

The variable $HOME inside of *tsu* is /data/data/com.termux/files/home/.suroot.

I don't know what more details to provide to make the description of the problem clearer. As far as I understand, *tsu* doesn't copy my environment and uses some default one.

**Comment by cswl** [comment]
The root user now has a seperate `HOME` directory to prevent file permission issues on normal Termux user.

For now, you would need to copy these dotfiles into roots `$HOME` directory.

**Comment by staunch-thomas** [comment]
Thank you. I've copied all of .vim* files and directories as well as .bashrc into .suroot/ and now everything works as expected.
