### ISSUE TITLE
tsu, No superuser binary detected

### ISSUE THREAD

**Issue by kotleni** [cswl/tsu#70]
![изображение](https://user-images.githubusercontent.com/38311102/92330988-c5e53d00-f07b-11ea-916e-c3d72b5a621e.png)

supersu

Just su - works

**Comment by pakbaz-dev** [comment]
Commit https://github.com/cswl/tsu/commit/5543412247ec8209e4ce776db2c7871f4fe3841b should fix this issue which will be included in the next release.
Try this and check if it solves the issue:
```
sed -E 's/^SU_BINARY_SEARCH=\(.*\)/SU_BINARY_SEARCH=("\/system\/xbin\/su" "\/system\/bin\/su" "\/su\/bin\/su")/' "$(whereis -b tsu | cut -d' ' -f 2)" > new_tsu && cp new_tsu "$(whereis -b tsu | cut -d' ' -f 2)" && rm new_tsu
```

**Comment by kotleni** [comment]
Yes, this is work. Su bin located in /su/bin/su
